### ISSUE TITLE
DS-HD1 - 31 is not a valid DeviceType

### ISSUE THREAD

**Issue by hgregorian** [pergolafabio/Hikvision-Addons#103]
### What happened?

Unable to use beta add-on with DS-HD1.  FWIW, it works with an older DS-KB6003-WIP.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.0-beta.17

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-04-10 21:20:37.467 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-04-10 21:20:37.473 | DEBUG    | __main__:main:26 - Importing Hikvision SDK
2023-04-10 21:20:37.474 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
2023-04-10 21:20:37.474 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-amd64/libhcnetsdk.so
2023-04-10 21:20:37.481 | DEBUG    | __main__:main:30 - Hikvision SDK loaded
2023-04-10 21:20:37.481 | DEBUG    | sdk.utils:setupSDK:86 - Initializing SDK
loop[2] find 2 mac and 0 ip
[2023-04-10 21:20:37.542][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/x86_64-linux-gnu/libz.so.1.2.11], hHandleRet[-1895863280]
[2023-04-10 21:20:37.542][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-04-10 21:20:37.542][INF] The COM:Core ver is 6.1.6.45, 2021_03_02. Async:1.
[2023-04-10 21:20:37.542][INF] This HCNetSDK ver is 6.1.6.45 Ver 2021_03_02.
2023-04-10 21:20:37.542 | DEBUG    | sdk.utils:setupSDK:100 - SDK initialized
2023-04-10 21:20:37.543 | DEBUG    | doorbell:__init__:41 - Setting up doorbell: Front Door
2023-04-10 21:20:37.543 | DEBUG    | doorbell:authenticate:48 - Logging into doorbell
[2023-04-10 21:20:37.543][INF] Login dev 192.168.1.148:8000.
[2023-04-10 21:20:37.543][INF] dwTotalNum[2048]
[2023-04-10 21:20:37.548][INF] Private connect 192.168.1.148:8000 sock=135 this=0x8f43c454 cmd=0x10000 port=49168
[2023-04-10 21:20:37.548][INF] LogonDev1 in[192.168.1.148:8000]
[2023-04-10 21:20:37.548][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libcrypto.so], hHandleRet[-1891343648]
[2023-04-10 21:20:37.548][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libssl.so], hHandleRet[-1891342416]
[2023-04-10 21:20:37.548][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-amd64/libcrypto.so]
[2023-04-10 21:20:37.548][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[/app/lib-amd64/libssl.so]
[2023-04-10 21:20:37.548][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload
[2023-04-10 21:20:37.548][INF] OpenSSL, Not All Function Loaded!
[2023-04-10 21:20:37.548][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]
[2023-04-10 21:20:37.548][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
Traceback (most recent call last):
  File "/app/main.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 42, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 61, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 31 is not a valid DeviceType
[2023-04-10 21:20:37.627][INF] COM_Logout[0][1]
[2023-04-10 21:20:37.637][DBG] CUserMgr::UnRegisterHeartProxy[0]
[2023-04-10 21:20:37.642][INF] Private connect 192.168.1.148:8000 sock=3 this=0x8f43c454 cmd=0x10100 port=49182
```

**Comment by pergolafabio** [comment]
Hi, the non-beta addon, was that working for you?

**Comment by pergolafabio** [comment]
can you also try beta 18 ? just updated a new one

**Comment by hgregorian** [comment]
Sure, just did (and thank you for taking a look so quickly).  New problem:

```
2023-04-11 11:23:50.342 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-04-11 11:23:50.348 | DEBUG    | __main__:main:26 - Importing Hikvision SDK
2023-04-11 11:23:50.349 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
2023-04-11 11:23:50.349 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-amd64/libhcnetsdk.so
2023-04-11 11:23:50.355 | DEBUG    | __main__:main:30 - Hikvision SDK loaded
2023-04-11 11:23:50.355 | DEBUG    | sdk.utils:setupSDK:86 - Initializing SDK
loop[2] find 2 mac and 0 ip
2023-04-11 11:23:50.434 | DEBUG    | sdk.utils:setupSDK:100 - SDK initialized
2023-04-11 11:23:50.435 | DEBUG    | doorbell:__init__:42 - Setting up doorbell: Front Door
2023-04-11 11:23:50.435 | DEBUG    | doorbell:authenticate:49 - Logging into doorbell
[2023-04-11 11:23:50.434][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/x86_64-linux-gnu/libz.so.1.2.11], hHandleRet[-1603396592]
[2023-04-11 11:23:50.434][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-04-11 11:23:50.434][INF] The COM:Core ver is 6.1.6.45, 2021_03_02. Async:1.
[2023-04-11 11:23:50.434][INF] This HCNetSDK ver is 6.1.6.45 Ver 2021_03_02.
[2023-04-11 11:23:50.435][INF] Login dev 192.168.1.148:8000.
[2023-04-11 11:23:50.435][INF] dwTotalNum[2048]
[2023-04-11 11:23:50.453][INF] Private connect 192.168.1.148:8000 sock=134 this=0xa0b27814 cmd=0x10000 port=45246
[2023-04-11 11:23:50.453][INF] LogonDev1 in[192.168.1.148:8000]
[2023-04-11 11:23:50.453][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libcrypto.so], hHandleRet[-1598876000]
[2023-04-11 11:23:50.454][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libssl.so], hHandleRet[-1598874768]
[2023-04-11 11:23:50.454][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-amd64/libcrypto.so]
[2023-04-11 11:23:50.454][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[/app/lib-amd64/libssl.so]
[2023-04-11 11:23:50.454][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload
[2023-04-11 11:23:50.454][INF] OpenSSL, Not All Function Loaded!
[2023-04-11 11:23:50.454][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]
[2023-04-11 11:23:50.454][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
2023-04-11 11:23:50.527 | DEBUG    | doorbell:authenticate:66 - Login returned user ID: 0
2023-04-11 11:23:50.527 | DEBUG    | doorbell:authenticate:67 - Doorbell serial number: 67834568664945654845496651878070824849504850484852505267678282695154535752565655, device type: HD
2023-04-11 11:23:50.527 | INFO     | doorbell:authenticate:69 - Connected to doorbell: Front Door
2023-04-11 11:23:50.527 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-04-11 11:23:50.527 | DEBUG    | event:register_handler:206 - Adding event handler ConsoleSTDOUT
2023-04-11 11:23:50.528 | INFO     | mqtt:__init__:91 - Setting up event handler: MQTT
2023-04-11 11:23:50.528 | DEBUG    | mqtt:__init__:102 - Setting up entities for Front Door
2023-04-11 11:23:50.528 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-04-11 11:23:50.529][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCVoiceTalk.so] SUCC
[2023-04-11 11:23:50.529][INF] AbilityAnalyze---Init-- start
[2023-04-11 11:23:50.529][DBG] AbilityAnalyze---Init-- over, DeviceList path [/app/lib-amd64/HCNetSDKCom/LocalXml/DeviceList.xml], load result[0]
[2023-04-11 11:23:50.530][INF] The COM:VoiceTalk ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.530][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCGeneralCfgMgr.so] SUCC
[2023-04-11 11:23:50.530][INF] The COM:HCGeneralCfgMgr ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.530][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCPlayBack.so] SUCC
[2023-04-11 11:23:50.530][INF] The COM:HCPlayback ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.530][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCIndustry.so] SUCC
[2023-04-11 11:23:50.530][INF] The COM:HCIndustry ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.531][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCDisplay.so] SUCC
[2023-04-11 11:23:50.531][INF] The COM:HCDisplay ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.531][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCPreview.so] SUCC
[2023-04-11 11:23:50.531][INF] The COM:Preview ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.531][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCAlarm.so] SUCC
[2023-04-11 11:23:50.531][INF] The COM:HCAlarm ver is 6.1.6.45, 2021_03_02.
[2023-04-11 11:23:50.533][INF] Private connect 192.168.1.148:8000 sock=134 this=0xa0b27814 cmd=0x117000 port=45256
2023-04-11 11:23:50.556 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: 
[2023-04-11 11:23:50.556][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-04-11 11:23:50.569][INF] [0][COM_CoreDevCfg_GetDeviceAbility] AbilityType 0x14, InbufLen=[0], OutbufLen[4096]
[2023-04-11 11:23:50.571][INF] Private connect 192.168.1.148:8000 sock=136 this=0xa0b27814 cmd=0x11000 port=45260
2023-04-11 11:23:50.619 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-04-11 11:23:50.623][INF] Private connect 192.168.1.148:8000 sock=136 this=0xa0b27814 cmd=0x117000 port=45270
2023-04-11 11:23:50.630 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: 
2023-04-11 11:23:50.630 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-04-11 11:23:50.630][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/IO/outputs], input size[0], max segment length[262144]
[2023-04-11 11:23:50.634][INF] Private connect 192.168.1.148:8000 sock=136 this=0xa0b27814 cmd=0x117000 port=45286
2023-04-11 11:23:50.653 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: 
Traceback (most recent call last):
  File "/app/main.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 52, in main
    mqtt = MQTTHandler(config.mqtt, doorbell_registry)
  File "/app/mqtt.py", line 132, in __init__
    num_doors = doorbell.get_num_outputs()
  File "/app/doorbell.py", line 227, in get_num_outputs
    raise RuntimeError("Unable to get the number of doors")
RuntimeError: Unable to get the number of doors
[2023-04-11 11:23:50.653][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/AccessControl/RemoteControl/door/capabilities], input size[0], max segment length[262144]
[2023-04-11 11:23:50.665][INF] COM_Logout[0][1]
[2023-04-11 11:23:50.668][DBG] CUserMgr::UnRegisterHeartProxy[0]
[2023-04-11 11:23:50.670][INF] Private connect 192.168.1.148:8000 sock=3 this=0xa0b27814 cmd=0x10100 port=45292
```

> can you also try beta 18 ? just updated a new one

**Comment by pergolafabio** [comment]
Hmm, does your doorstation have relay outputs to open door? What we do upon connect, is sending an ISAPI to get the number of relays, but seems that fails... Can you try defining the relays manually? , like in this example config?

```
- name: DS-KD8003
  ip: 192.168.0.70
  username: admin
  password: XXX
  output_relays: 2
```

**Comment by pergolafabio** [comment]
Can you do me also a favor and run thse 2 commands below in an SSH terminal? and show me the output?
Offcourse change IP and the password below :-)

```
curl -i --digest -u admin:xxx http://192.168.0.70/ISAPI/AccessControl/RemoteControl/door/capabilities
curl -i --digest -u admin:xxx http://192.168.0.70/ISAPI/System/IO/outputs
```

**Comment by pergolafabio** [comment]
Can you give me an update?

**Comment by hgregorian** [comment]
So, this camera model is a little “funny” in that ISAPI requests result in 404’s.  It’s probably outside the scope of this project, so I’d understand if supporting is not possible or not in your interests.

That said, adding a relay in configuration does allow the add-on to start and a device with entities is present.

Here are the latest logs:

`
2023-04-22 10:42:03.330 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-04-22 10:42:03.336 | DEBUG    | __main__:main:26 - Importing Hikvision SDK
2023-04-22 10:42:03.337 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
2023-04-22 10:42:03.337 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-amd64/libhcnetsdk.so
2023-04-22 10:42:03.344 | DEBUG    | __main__:main:30 - Hikvision SDK loaded
2023-04-22 10:42:03.344 | DEBUG    | sdk.utils:setupSDK:86 - Initializing SDK
loop[2] find 2 mac and 0 ip
2023-04-22 10:42:03.410 | DEBUG    | sdk.utils:setupSDK:100 - SDK initialized
2023-04-22 10:42:03.411 | DEBUG    | doorbell:__init__:42 - Setting up doorbell: Front Door
2023-04-22 10:42:03.411 | DEBUG    | doorbell:authenticate:49 - Logging into doorbell
[2023-04-22 10:42:03.410][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/x86_64-linux-gnu/libz.so.1.2.11], hHandleRet[995081232]
[2023-04-22 10:42:03.410][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-04-22 10:42:03.410][INF] The COM:Core ver is 6.1.6.45, 2021_03_02. Async:1.
[2023-04-22 10:42:03.410][INF] This HCNetSDK ver is 6.1.6.45 Ver 2021_03_02.
[2023-04-22 10:42:03.411][INF] Login dev 192.168.1.148:8000.
[2023-04-22 10:42:03.411][INF] dwTotalNum[2048]
[2023-04-22 10:42:03.417][INF] Private connect 192.168.1.148:8000 sock=134 this=0x3b941af4 cmd=0x10000 port=58114
[2023-04-22 10:42:03.417][INF] LogonDev1 in[192.168.1.148:8000]
[2023-04-22 10:42:03.417][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libcrypto.so], hHandleRet[999602560]
[2023-04-22 10:42:03.417][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libssl.so], hHandleRet[999603792]
[2023-04-22 10:42:03.417][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-amd64/libcrypto.so]
[2023-04-22 10:42:03.417][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[/app/lib-amd64/libssl.so]
[2023-04-22 10:42:03.417][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload
[2023-04-22 10:42:03.417][INF] OpenSSL, Not All Function Loaded!
[2023-04-22 10:42:03.417][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]
[2023-04-22 10:42:03.417][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
2023-04-22 10:42:03.586 | DEBUG    | doorbell:authenticate:66 - Login returned user ID: 0
2023-04-22 10:42:03.586 | DEBUG    | doorbell:authenticate:67 - Doorbell serial number: 67834568664945654845496651878070824849504850484852505267678282695154535752565655, device type: HD
2023-04-22 10:42:03.586 | INFO     | doorbell:authenticate:69 - Connected to doorbell: Front Door
2023-04-22 10:42:03.586 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-04-22 10:42:03.586 | DEBUG    | event:register_handler:206 - Adding event handler ConsoleSTDOUT
2023-04-22 10:42:03.587 | INFO     | mqtt:__init__:91 - Setting up event handler: MQTT
2023-04-22 10:42:03.587 | DEBUG    | mqtt:__init__:102 - Setting up entities for Front Door
2023-04-22 10:42:03.587 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-04-22 10:42:03.588][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCVoiceTalk.so] SUCC
[2023-04-22 10:42:03.588][INF] AbilityAnalyze---Init-- start
[2023-04-22 10:42:03.588][DBG] AbilityAnalyze---Init-- over, DeviceList path [/app/lib-amd64/HCNetSDKCom/LocalXml/DeviceList.xml], load result[0]
[2023-04-22 10:42:03.588][INF] The COM:VoiceTalk ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.589][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCGeneralCfgMgr.so] SUCC
[2023-04-22 10:42:03.589][INF] The COM:HCGeneralCfgMgr ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.589][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCPlayBack.so] SUCC
[2023-04-22 10:42:03.589][INF] The COM:HCPlayback ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.589][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCIndustry.so] SUCC
[2023-04-22 10:42:03.589][INF] The COM:HCIndustry ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.589][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCDisplay.so] SUCC
[2023-04-22 10:42:03.590][INF] The COM:HCDisplay ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.590][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCPreview.so] SUCC
[2023-04-22 10:42:03.590][INF] The COM:Preview ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.590][DBG] CComBase::Load, Load szDllPath[/app/lib-amd64/HCNetSDKCom/libHCAlarm.so] SUCC
[2023-04-22 10:42:03.590][INF] The COM:HCAlarm ver is 6.1.6.45, 2021_03_02.
[2023-04-22 10:42:03.603][INF] Private connect 192.168.1.148:8000 sock=134 this=0x3b941af4 cmd=0x117000 port=58118
2023-04-22 10:42:03.654 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: 
[2023-04-22 10:42:03.654][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
2023-04-22 10:42:03.670 | DEBUG    | doorbell:user_config:166 - Using the configured number of switches: 2
2023-04-22 10:42:03.670 | DEBUG    | mqtt:__init__:133 - Configuring 2 door switches
2023-04-22 10:42:03.671 | DEBUG    | event:register_handler:206 - Adding event handler MQTT
2023-04-22 10:42:03.672 | DEBUG    | mqtt_input:__init__:19 - Setting up MQTTInput
2023-04-22 10:42:03.672 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-04-22 10:42:03.745][INF] Private connect 192.168.1.148:8000 sock=142 this=0x3b941af4 cmd=0x117000 port=58128
2023-04-22 10:42:03.768 | DEBUG    | sdk.utils:call_ISAPI:162 - Response status: 
2023-04-22 10:42:03.773 | DEBUG    | event:start:227 - Registering callback function using SDK
2023-04-22 10:42:03.773 | DEBUG    | doorbell:setup_alarm:80 - Arming the device via SDK
[2023-04-22 10:42:03.768][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-04-22 10:42:03.777][INF] Private connect 192.168.1.148:8000 sock=157 this=0x3b941af4 cmd=0x111020 port=58136
2023-04-22 10:42:03.812 | DEBUG    | input:loop_forever:29 - Waiting for input command
[2023-04-22 10:42:58.856][DBG] Alarm chan [0] recv timeout[2]!
[2023-04-22 10:43:08.850][DBG] Alarm chan [0] recv timeout[2]!
[2023-04-22 10:43:23.856][DBG] Alarm chan [0] recv timeout[2]!
[2023-04-22 10:43:33.871][DBG] Alarm chan [0] recv timeout[2]!
[2023-04-22 10:43:58.887][DBG] Alarm chan [0] recv timeout[2]!
`

> Can you give me an update?

**Comment by pergolafabio** [comment]
Hi , those logs look ok to me, everything is started it seems?
Does it create now an mqtt device? You should see all entities en sensors being created now?

**Comment by pergolafabio** [comment]
hey @hgregorian , are you still using this hikvision addon ?
