### ISSUE TITLE
DS-K1T501SF door lock not exposed

### ISSUE THREAD

**Issue by eumanecs** [pergolafabio/Hikvision-Addons#117]
### What happened?

I have AccessControl Terminal DS-K1T501SF dos not support ISAPI, looks like it dos not exposes to plugin door lock  expose the locks in the payload.

I have been using fiddler i has able to capter actual POST
POST https://apiieu.hik-connect.com/api/device/transmit HTTP/1.1
Host: apiieu.hik-connect.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Connection: keep-alive
Accept: application/json
User-Agent: HikConnect/20230606 (iPhone; iOS 16.5; Scale/3.00)
Accept-Language: en-LV;q=1, ru-LV;q=0.9, lv-LV;q=0.8
Accept-Encoding: gzip, deflate, br
Content-Length: 569

When unlocked from Hik-connect cloud in the body of post message there is provided aditinal 6 digit password to operate the unlock action

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

2.1 & 3.0.0

### Installation type

Home Assistant add-on

### Relevant log output

```Text
Version 2.1
2023-06-17 05:18:59.847 | DEBUG    | config:loadConfig:31 - Loading config from file
loop[2] find 6 mac and 12 ip
2023-06-17 05:19:00.233 | ERROR    | __main__:<module>:142 - NET_DVR_Login_V30 failed, error code = 153

Verion 3.0.0
2023-06-17 05:17:03.184 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-06-17 05:17:03.207 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
Traceback (most recent call last):
  File "/app/main.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 42, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 62, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 861 is not a valid DeviceType
```

### Relevant configuration

```YAML
template:
  - sensor:
      - name: hikvision_door
        state: "off"
      - name: hikvision_callstatus
        state: "off"
      - name: hikvision_motion
        state: "off"
      - name: hikvision_tamper
        state: "off"
      - name: hikvision_dismiss
        state: "off"
service: hassio.addon_stdin
data:
  addon: aff2db71_hikvision_doorbell
  input: unlock front_door 1
```

### Anything else?

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/cdd12760-16fd-4a6a-8d21-bd031955e8fe)

**Comment by pergolafabio** [comment]
Hi, Hikconnect indeed doesnt use ISAPI, but build on SDK also (i believe)

I have added your device 861 as a valid device type in beta 20, will release it soon...

The beta addon has several methods to open door in case one method fails

**Comment by pergolafabio** [comment]
beta 20 released, can you try?

**Comment by eumanecs** [comment]
just reinstaled beta 20 release got log  2023-06-17 11:49:30.771 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-06-17 11:49:30.799 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
2023-06-17 11:49:31.116 | INFO     | doorbell:authenticate:70 - Connected to doorbell: Durvis
2023-06-17 11:49:31.117 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-06-17 11:49:31.117 | INFO     | mqtt:__init__:91 - Setting up event handler: MQTT
Traceback (most recent call last):
  File "/app/main.py", line 91, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 52, in main
    mqtt = MQTTHandler(config.mqtt, doorbell_registry)
  File "/app/mqtt.py", line 132, in __init__
    num_doors = doorbell.get_num_outputs()
  File "/app/doorbell.py", line 228, in get_num_outputs
    raise RuntimeError("Unable to get the number of doors")
RuntimeError: Unable to get the number of doors

**Comment by pergolafabio** [comment]
Its using indeed ISAPI to get the relays, can you configure them manually as described here:

https://github.com/pergolafabio/Hikvision-Addons/blob/main/doorbell_beta/DOCS.md

With output_relays ...

**Comment by eumanecs** [comment]
Not shure what i am dooing wrong

my configuration look lik this


# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text-to-speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# configuration.yaml
service: hassio.addon_stdin
data:
  addon: aff2db71_hikvision_doorbell
  input: unlock front_door 1




and


![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/7a2f3f6e-9fd3-465c-8afb-7b020e6272d0)

**Comment by pergolafabio** [comment]
Hi, the config looks correct, but check your mqtt integration, there should be a device be created, with all sensors and relays, you don't need to use that service

**Comment by eumanecs** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/fba77a4e-6e6f-4acd-a2ad-e5494faee83c)

**Comment by pergolafabio** [comment]
goto settings , integrations, mqtt, should look like this:

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/6fbb8ef4-010d-4c55-8ac1-94a9a035d1f6)
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/f12e4d09-cdce-43de-9fa4-6063ca09db18)

**Comment by pergolafabio** [comment]
remove that service: part from your configuration, thats incorrect, is not needed

**Comment by pergolafabio** [comment]
You don't need to touch any yaml file, if you use beta addon, all sensors and services will be created automatically as an mqtt device

**Comment by eumanecs** [comment]
my UI looks diferent i dont have integrations under settings i have removed service part from my configuration
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/e1448a9c-c638-4e02-bb7c-1cbde34e2373)

**Comment by eumanecs** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/e82a43d2-ef36-47d5-bb88-9919afe62961)

**Comment by pergolafabio** [comment]
offcourse you have :-) , there you will see the integrations, then click on mqtt 

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/d2f61e62-25ac-4bba-bf6b-59c31bfe31d6)

**Comment by eumanecs** [comment]
Supper, but it seams that Hikvisin door bell beta stops working
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/f5e761c4-57ff-4912-94d9-6189f876cf96)

**Comment by eumanecs** [comment]
2023-06-17 13:02:36.230 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-06-17 13:02:36.238 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 0 ip
2023-06-17 13:02:36.775 | INFO     | doorbell:authenticate:70 - Connected to doorbell: Front door
2023-06-17 13:02:36.775 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-06-17 13:02:36.775 | INFO     | mqtt:__init__:91 - Setting up event handler: MQTT
2023-06-17 13:02:37.056 | ERROR    | __main__:<module>:96 - Error while listening to events in Front door: Failed to receive data from the device. Error code:9

**Comment by eumanecs** [comment]
and this is how MQTT log file looks
2023-06-17 12:58:28: New client connected from 172.30.33.3:60135 as auto-C2FC719B-F14C-0A8A-3426-6FF983A008B1 (p2, c1, k60, u'addons').
2023-06-17 12:58:28: New connection from 172.30.33.3:50477 on port 1883.
2023-06-17 12:58:28: New client connected from 172.30.33.3:50477 as auto-AF3D3CA8-64E6-B9BB-F7C7-9C6E708E0FCE (p2, c1, k60, u'addons').
2023-06-17 12:58:28: New connection from 172.30.33.3:56825 on port 1883.
2023-06-17 12:58:28: New client connected from 172.30.33.3:56825 as auto-50175249-3CE0-AF12-C23D-CBAA4ACF0C25 (p2, c1, k60, u'addons').
2023-06-17 12:58:28: New connection from 172.30.33.3:35233 on port 1883.
2023-06-17 12:58:28: New client connected from 172.30.33.3:35233 as auto-138E922F-1A6C-BF5F-199F-90FCD751B697 (p2, c1, k60, u'addons').
2023-06-17 12:58:28: Client auto-138E922F-1A6C-BF5F-199F-90FCD751B697 closed its connection.
2023-06-17 12:58:28: Client auto-50175249-3CE0-AF12-C23D-CBAA4ACF0C25 closed its connection.
2023-06-17 12:58:28: Client auto-AF3D3CA8-64E6-B9BB-F7C7-9C6E708E0FCE closed its connection.
2023-06-17 12:58:28: Client auto-C2FC719B-F14C-0A8A-3426-6FF983A008B1 closed its connection.
2023-06-17 12:58:28: Client auto-85C183D9-8DC8-19DE-2801-6C811B7AC73D closed its connection.
2023-06-17 12:58:28: Client auto-7FB1B381-8891-E4AD-CC62-85B3D9DB7D67 closed its connection.
2023-06-17 12:58:28: Client auto-52B27465-27EA-9352-9783-8C18E2559436 closed its connection.
2023-06-17 12:58:30: New connection from 172.30.33.3:45797 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:45797 as auto-1F12AFDE-2374-F898-23AB-D59D3BCD429A (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New connection from 172.30.33.3:36929 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:36929 as auto-8D889BE9-1A90-3440-92BD-AD6937BA1002 (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New connection from 172.30.33.3:37847 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:37847 as auto-DE4E1DEB-42C9-5DFF-86F9-27EA188ED1AD (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New connection from 172.30.33.3:60435 on port 1883.
2023-06-17 12:58:30: New connection from 172.30.33.3:55755 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:60435 as auto-BB99A134-FCA8-FB88-A650-6A2D30AC5B6A (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New client connected from 172.30.33.3:55755 as auto-389176B6-7129-B2D5-8300-C029CD16447E (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New connection from 172.30.33.3:45891 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:45891 as auto-B05CA5AA-FF04-CAB6-34C2-E1A266DA4842 (p2, c1, k60, u'addons').
2023-06-17 12:58:30: New connection from 172.30.33.3:50981 on port 1883.
2023-06-17 12:58:30: New client connected from 172.30.33.3:50981 as auto-A8F0D6D8-0315-01CC-5286-589827D9FD3C (p2, c1, k60, u'addons').
2023-06-17 12:58:30: Client auto-A8F0D6D8-0315-01CC-5286-589827D9FD3C closed its connection.
2023-06-17 12:58:30: Client auto-B05CA5AA-FF04-CAB6-34C2-E1A266DA4842 closed its connection.
2023-06-17 12:58:30: Client auto-389176B6-7129-B2D5-8300-C029CD16447E closed its connection.
2023-06-17 12:58:30: Client auto-BB99A134-FCA8-FB88-A650-6A2D30AC5B6A closed its connection.
2023-06-17 12:58:30: Client auto-DE4E1DEB-42C9-5DFF-86F9-27EA188ED1AD closed its connection.
2023-06-17 12:58:30: Client auto-8D889BE9-1A90-3440-92BD-AD6937BA1002 closed its connection.
2023-06-17 12:58:30: Client auto-1F12AFDE-2374-F898-23AB-D59D3BCD429A closed its connection.
2023-06-17 12:58:32: New connection from 172.30.33.3:47237 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:47237 as auto-D2EFA704-7BBF-9391-C8A7-00DB0B2489DB (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:40993 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:40993 as auto-DF89E541-6B7B-F255-19C1-607152765B0F (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:35417 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:35417 as auto-36AC7CCA-AE9B-5EC0-4380-CACA22F61A9E (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:33309 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:33309 as auto-846F9BCF-9FC6-57B9-BBD9-007826D5FEC7 (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:49435 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:49435 as auto-489E0ACA-61F2-6E24-D7C8-267BAEDB313F (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:46793 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:46793 as auto-5A8A6CB1-3B85-4F59-FF6C-8FEC9DC6C145 (p2, c1, k60, u'addons').
2023-06-17 12:58:32: New connection from 172.30.33.3:49113 on port 1883.
2023-06-17 12:58:32: New client connected from 172.30.33.3:49113 as auto-E57CD7C0-FEE2-5B2F-F45D-2F5AE0D24AC2 (p2, c1, k60, u'addons').
2023-06-17 12:58:32: Client auto-E57CD7C0-FEE2-5B2F-F45D-2F5AE0D24AC2 closed its connection.
2023-06-17 12:58:32: Client auto-5A8A6CB1-3B85-4F59-FF6C-8FEC9DC6C145 closed its connection.
2023-06-17 12:58:32: Client auto-489E0ACA-61F2-6E24-D7C8-267BAEDB313F closed its connection.
2023-06-17 12:58:32: Client auto-846F9BCF-9FC6-57B9-BBD9-007826D5FEC7 closed its connection.
2023-06-17 12:58:32: Client auto-36AC7CCA-AE9B-5EC0-4380-CACA22F61A9E closed its connection.
2023-06-17 12:58:32: Client auto-DF89E541-6B7B-F255-19C1-607152765B0F closed its connection.
2023-06-17 12:58:32: Client auto-D2EFA704-7BBF-9391-C8A7-00DB0B2489DB closed its connection.
2023-06-17 12:58:34: New connection from 172.30.33.3:43983 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:43983 as auto-706BBF87-1934-612C-F071-4B09281F9ED6 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:34941 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:34941 as auto-08B84C9F-5C4B-7B3A-2AF6-D11EB3266274 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:44989 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:44989 as auto-B080FEEC-43B2-F6DE-FF39-B28D27497BF4 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:34235 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:34235 as auto-840CDACB-6135-DDB5-F34C-B79068E6B329 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:46393 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:46393 as auto-9A6BC441-6B98-3AEF-158E-3B13D96C9AD2 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:57229 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:57229 as auto-10B9C34C-3C07-5282-3E8D-1ACA42D607E7 (p2, c1, k60, u'addons').
2023-06-17 12:58:34: New connection from 172.30.33.3:43295 on port 1883.
2023-06-17 12:58:34: New client connected from 172.30.33.3:43295 as auto-DC21BF49-6566-36F5-77B6-59791893C3CD (p2, c1, k60, u'addons').
2023-06-17 12:58:34: Client auto-DC21BF49-6566-36F5-77B6-59791893C3CD closed its connection.
2023-06-17 12:58:34: Client auto-10B9C34C-3C07-5282-3E8D-1ACA42D607E7 closed its connection.
2023-06-17 12:58:34: Client auto-9A6BC441-6B98-3AEF-158E-3B13D96C9AD2 closed its connection.
2023-06-17 12:58:34: Client auto-840CDACB-6135-DDB5-F34C-B79068E6B329 closed its connection.
2023-06-17 12:58:34: Client auto-B080FEEC-43B2-F6DE-FF39-B28D27497BF4 closed its connection.
2023-06-17 12:58:34: Client auto-08B84C9F-5C4B-7B3A-2AF6-D11EB3266274 closed its connection.
2023-06-17 12:58:34: Client auto-706BBF87-1934-612C-F071-4B09281F9ED6 closed its connection.
2023-06-17 12:59:43: New connection from 172.30.32.2:54634 on port 1883.
2023-06-17 12:59:43: Client <unknown> closed its connection.
2023-06-17 13:00:54: New connection from 172.30.33.3:38295 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:38295 as auto-D737CF1C-DF86-B78F-A9AD-C4D03EE06DC7 (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:41901 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:41901 as auto-867F99C4-9FED-72E9-325B-0C30A2C7634A (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:52891 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:52891 as auto-D566A548-9482-C0A9-5C96-84E828134C77 (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:49373 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:49373 as auto-A36165CE-1C8B-DA2F-722E-83079BA70109 (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:48161 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:48161 as auto-6EC31EEB-FA4A-FAB8-9B70-F3F76EDBDC5F (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:42119 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:42119 as auto-290EAFD8-E33F-0766-2CDC-ADDBB357BD36 (p2, c1, k60, u'addons').
2023-06-17 13:00:54: New connection from 172.30.33.3:40703 on port 1883.
2023-06-17 13:00:54: New client connected from 172.30.33.3:40703 as auto-3FDB3FAA-7CAA-5DBB-75BD-C25429F0D7F5 (p2, c1, k60, u'addons').
2023-06-17 13:00:54: Client auto-3FDB3FAA-7CAA-5DBB-75BD-C25429F0D7F5 closed its connection.
2023-06-17 13:00:54: Client auto-290EAFD8-E33F-0766-2CDC-ADDBB357BD36 closed its connection.
2023-06-17 13:00:54: Client auto-6EC31EEB-FA4A-FAB8-9B70-F3F76EDBDC5F closed its connection.
2023-06-17 13:00:54: Client auto-A36165CE-1C8B-DA2F-722E-83079BA70109 closed its connection.
2023-06-17 13:00:54: Client auto-D566A548-9482-C0A9-5C96-84E828134C77 closed its connection.
2023-06-17 13:00:54: Client auto-867F99C4-9FED-72E9-325B-0C30A2C7634A closed its connection.
2023-06-17 13:00:54: Client auto-D737CF1C-DF86-B78F-A9AD-C4D03EE06DC7 closed its connection.

**Comment by eumanecs** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/c396221f-3813-4d62-bd8e-4d6ecb4b2a21)



By the way i was able to ssh to my AccessControl terminal DS-K1T501SF wit root login may be i ca do som door unlock comand by som sip comand just for info

**Comment by pergolafabio** [comment]
I need to have a look later for that error 9 ...

There is also an hikconnect integration, using cloud, maybe you can use that one instead of this addon if you only want to open door?

**Comment by pergolafabio** [comment]
Hmm, seems error 9 , just means, fail to read data from device, can you try maybe rebooting it?

**Comment by eumanecs** [comment]
Yes, i wan only open door, my ultimate gool is to have some curl comand or http reqest to unlock the dor and latter to put that reqest on home bridide  to control the door with iphone wih siri voice using  https://github.com/TheRealSimon42/homebridge-http-lock-ultimate
 
i was usin this sorce:
 https://github.com/judge/homebridge-hikconnect
 but seam it's its buil from som revers eninering fom your homeassistant github code, so it dos not exposes my lock. 
and unfortunatlu no suppoert for ISAPI for my deviice DS-K1T501SF

**Comment by pergolafabio** [comment]
You can use the hikconnect integration in HA, that should work for you, you will find it in HACS

**Comment by pergolafabio** [comment]
https://github.com/tomasbedrich/home-assistant-hikconnect

**Comment by eumanecs** [comment]
I have been in contact with 
[tomasbedrich](https://github.com/tomasbedrich) 

his replay was

Thanks for the logs. It seems your device does not expose the locks in the payload, the plugins looks for 'lockNum' property and it's not present in your case.
I don't have a device like yours so it's pretty complicated to reverse engineer what happens when you click unlock in the application. If you could do that (listen for web traffic while press the button in the application) I could check if I could do something.

**Comment by eumanecs** [comment]
i started to paly with the fiddler the problem is that  cant repaly POST comand as the body part of the post all the time is diferent https://apiieu.hik-connect.com/api/device/transmit HTTP/1.1
Host: apiieu.hik-connect.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Connection: keep-alive
Accept: application/json
User-Agent: HikConnect/20230606 (iPhone; iOS 16.5; Scale/3.00)
Accept-Language: en-LV;q=1, ru-LV;q=0.9, lv-LV;q=0.8
Accept-Encoding: gzip, deflate, br
Content-Length: 569

**Comment by pergolafabio** [comment]
Are you using android or iphone with fiddler?

**Comment by pergolafabio** [comment]
when i started before with hikconnect, i have an indoor station, i need to send unlock to that device:

i saw in fiddler:  (removed my serial number + token)

```


PUT /v3/devconfig/v1/call/QXXXXXXXX/1/remote/unlock?srcId=1&lockId=0&userType=0 HTTP/1.1
clientType: 55
osVersion: 5.1.1
clientVersion: 4.14.1.0407
netType: WIFI
clientNo: google_play
appChannel: hikvision
customno: 1000002
featureCode: b547bcdd76b2f2c93e0956114a6f8665
sessionId: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
areaId: 111
lang: en-US
appId: HikConnect
Content-Length: 0
Host: apiieu.hik-connect.com
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.12.1

```

**Comment by pergolafabio** [comment]
yes, body part is indeed differen, you need to send the sessionID , its a token

you can create a sensor in HA, to grab the sessionID  , here is an example, you can see it all in fiddler, make sure to change the payload, i have it in secret, its actuallt the login part, just copy/past it from fiddler

```
  - platform: rest
    name: hikconnect_login
    scan_interval: 7200
    resource: "https://apiieu.hik-connect.com/v3/users/login/v2"
    headers:
      customno: 1000002
      appChannel: "hikvision"
      Content-Type: "application/x-www-form-urlencoded"
      featureCode: "b547bcdd76b2f2c93e0956114a6f8665"
      lang: "en-US"
      clientVersion: "4.14.1.0407"
      appId: "HikConnect"
      sessionId: ""
      clientType: 55
      clientNo: "google_play"
      areaId: 111
      netType: "WIFI"
      osVersion: "5.1.1"   
    method: POST
    payload: !secret hikvision_payload
    value_template: "Hikconnect Login"    
    json_attributes:
    - loginSession 
```
you can see the payload in the "textview" below , its a long huge string

![image](https://github.com/pergolafabio/Hikvision-Addons/assets/43251136/4aa81de5-76db-440f-b87e-279f2f2f8de5)

**Comment by eumanecs** [comment]
Iphone 13 mini ios 16.05 i was able to capture all trafick very well. I was not able to logi in to Hikconect app when proxy was activeted, but thet i log in on hikconect app with my credentials and afterwards enabled proxy on my phone and afterward i am able to cappuure all the trafick

**Comment by pergolafabio** [comment]
yeah, once you have the sensor, you can build actions/scripts, based on the sessionID

**Comment by pergolafabio** [comment]
for example;, here is a reject command, as you see i use the sessionID from the sensor:


`hikconnect_callsignal_3_reject-: "curl -X PUT --header \"sessionId: {{ state_attr('sensor.hikconnect_login', 'loginSession').sessionId }}\" https://apiieu.hik-connect.com/v3/devconfig/v1/call/XXXXXXX/operation?cmdId=3&handler=e6ldym"`

just copy paste the command from fiddler

**Comment by eumanecs** [comment]
i am able to get my faturecode but then i am stuck with what next, idealy if somone can make some plugin were i put my varialbes like customno and featurecode

**Comment by pergolafabio** [comment]
see above, i copy pasted everything you need

**Comment by pergolafabio** [comment]
first you need the sensor, thats the most important one, you need the sessionID token, that token is always needed to send your commands, like open door

**Comment by eumanecs** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/8ddcd278-27fe-43e4-834f-3e037d1efd9d)

**Comment by pergolafabio** [comment]
yes, with that session id, you can send commands, but remember, the session is is only valid for some hours , its a temp token
thats why i created a rest sensor with scan interval 7200 sec

**Comment by eumanecs** [comment]
My post looks like this 
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/12eaa39a-3814-49cb-a615-0d0b3afbfa56)

**Comment by eumanecs** [comment]
![image](https://github.com/pergolafabio/Hikvision-Addons/assets/83247254/360d78fa-e57d-4afb-b242-c9cd8dcc2da2)

**Comment by eumanecs** [comment]
There I am stuck. What is sensor my serial device number? What is the header label name in fiddler for sensor?
 And wat is the payload is it session id value? 
Is the feature code header label name for the token?

What are the essential header label names from fiddler I should use?

**Comment by pergolafabio** [comment]
You can all see it in fiddler, see my posts above

**Comment by eumanecs** [comment]
Ok i will investigate that.  bay the way, i have rebooted device  if you can take a look when you will have a time   error 9 - fail to read data from device on home assitant. toady i will not boter you any more, hav a nice weekend.

**Comment by pergolafabio** [comment]
Ok, will have a look , have a nice weekend!

**Comment by eumanecs** [comment]
Hello i have managed to create the python scrip to unlock my door the key values for me was:
this info is aquered up on login:
token
voipToken
session_id
In order to unlock the door i need to login in to Hikconect app with the username and password go to the Access control device DS-K1T501SF in the app and there is door i need to provide extra 6 digit code to punch in order to unlock the door. if somone needs i can sher the Pyton script with masked privad data. pergolafabio let me know if you need somthing from Fiddler Everywhere i have still 5 days free trieal licence.

**Comment by pergolafabio** [comment]
Hi, no need for it
This addon is not based on Hikconnect, but uses the SDK, maybe you can provide the info thomas, who is the owner for the hikconnect integration? he can benefit from it?

Thnx anyway!! appreciated

**Comment by pergolafabio** [comment]
btw, if you use fiddler classic, its a free version, no trial then

**Comment by pergolafabio** [comment]
as for error 9 , not sure  i can do anything about it :-( 
Is it an old device you have? maybe a firmware upgrade?

**Comment by eumanecs** [comment]
Yes its several years old, I have some custom firmware on it have installed Portugies version of it that had special functionality there were folks that helped to unpack the firmware and access audio files we have replaced and then package it back.

**Comment by pergolafabio** [comment]
ah,  maybe some issue on it to retrieve the events by sdk :-(

**Comment by eumanecs** [comment]
i dont wan to upgarde there were some scripts repackFirmwareH5.py and unpackFirmwareH5 and unpack.sh repack.sh i was using.

**Comment by pergolafabio** [comment]
ok, maybe you can ask on community forum if someone added the device in the addon, that way we can rule out the issue wirth firmware maybe? gonna close for now, dont think i can do anything now :-(
