### ISSUE TITLE
Fallback to output_relays = 2 if ISAPI call fails

### ISSUE THREAD

**Issue by pergolafabio** [pergolafabio/Hikvision-Addons#118]
### What happened?

On some devices the ISAPI command doesnt work to get output relays, we have to fallback to a static number instead of error out

```
2023-06-17 11:49:31.117 | INFO | mqtt:init:91 - Setting up event handler: MQTT
Traceback (most recent call last):
File "/app/main.py", line 91, in
asyncio.run(main())
File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/app/main.py", line 52, in main
mqtt = MQTTHandler(config.mqtt, doorbell_registry)
File "/app/mqtt.py", line 132, in init
num_doors = doorbell.get_num_outputs()
File "/app/doorbell.py", line 228, in get_num_outputs
raise RuntimeError("Unable to get the number of doors")
RuntimeError: Unable to get the number of doors
```

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

beta 

### Installation type

Home Assistant add-on

**Comment by pergolafabio** [comment]
added a better comment for users, when no outputs are found

https://github.com/pergolafabio/Hikvision-Addons/commit/3e0b5a32fa019c8357911b9cea74671aad66e101
