### ISSUE TITLE
Support for different model doorbell

### ISSUE THREAD

**Issue by shizlanski** [pergolafabio/Hikvision-Addons#139]
### What happened?

My doorbell is not in the list of supported devices. I am wondering if it is possible to add?
I have a DS-K1T341AM.

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.2

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2023-09-06 09:51:43.082 | DEBUG    | config:load_mqtt_config:130 - Loading MQTT configuration from supervisor
2023-09-06 09:51:43.083 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-09-06 09:51:43.108 | DEBUG    | __main__:main:31 - Importing Hikvision SDK
2023-09-06 09:51:43.114 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: aarch64
2023-09-06 09:51:43.115 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-aarch64/libhcnetsdk.so
hpr tls index{3}
2023-09-06 09:51:43.147 | DEBUG    | __main__:main:35 - Hikvision SDK loaded
2023-09-06 09:51:43.148 | DEBUG    | sdk.utils:setupSDK:86 - Initializing SDK
loop[2] find 2 mac and 0 ip
[2023-09-06 09:51:43.176][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/aarch64-linux-gnu/libz.so.1.2.11], hHandleRet[-1576750400]
[2023-09-06 09:51:43.176][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-09-06 09:51:43.176][INF] The COM:Core ver is 6.1.8.101, 2021_12_10. Async:1.
2023-09-06 09:51:43.176 | DEBUG    | sdk.utils:setupSDK:100 - SDK initialized
[2023-09-06 09:51:43.176][INF] This HCNetSDK ver is 6.1.8.101 Ver 2021_12_10.
2023-09-06 09:51:43.177 | DEBUG    | doorbell:__init__:44 - Setting up doorbell: Gate
2023-09-06 09:51:43.178 | DEBUG    | doorbell:authenticate:51 - Logging into doorbell
[2023-09-06 09:51:43.179][INF] Login dev 192.168.1.128:8000.
[2023-09-06 09:51:43.179][INF] dwTotalNum[2048]
[2023-09-06 09:51:43.180][INF] Private connect 192.168.1.128:8000 sock=7 this=0xa23ee344 cmd=0x10000 port=46840
[2023-09-06 09:51:43.180][INF] LogonDev1 in[192.168.1.128:8000]
[2023-09-06 09:51:43.181][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-aarch64/libcrypto.so], hHandleRet[-1573089888]
[2023-09-06 09:51:43.182][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-aarch64/libssl.so], hHandleRet[-1572909968]
[2023-09-06 09:51:43.183][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-aarch64/libcrypto.so]
[2023-09-06 09:51:43.183][INF] SSLTRANSAPI::IsAllAPILoaded, SSL_library_init Unload
[2023-09-06 09:51:43.183][INF] OpenSSL, Not All Function Loaded!
[2023-09-06 09:51:43.183][INF] SSLTRANSAPI::PrintVersion, OpenSSL version info [OpenSSL 1.1.1i  8 Dec 2020]
[2023-09-06 09:51:43.183][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[6], m_fnTLSServerMethod
Traceback (most recent call last):
  File "/app/main.py", line 96, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 47, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 64, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 10503 is not a valid DeviceType
[2023-09-06 09:51:43.966][INF] COM_Logout[0][1]
[2023-09-06 09:51:43.969][DBG] CUserMgr::UnRegisterHeartProxy[0]
[2023-09-06 09:51:43.970][INF] Private connect 192.168.1.128:8000 sock=3 this=0xa23ee344 cmd=0x10100 port=46842
```

### Anything else?

https://www.hikvision.com/au-en/products/Access-Control-Products/Face-Recognition-Terminals/Value-Series/ds-k1t341am/

**Comment by pergolafabio** [comment]
Hi

I have added that device, but i added it in beta 35
So can you stop the addon, copy the config, install beta 35 addon, and paste the config? Can you try to see if it can login and create sensors?

You can also enable debug for first time:

```
log_level: DEBUG
sdk_log_level: DEBUG
```

**Comment by shizlanski** [comment]
Looks like that mostly worked.

I noticed there is no way to open the attached gate?
I saw a couple errors in the log, not sure if they mean anything.
Thanks for all your work.

> [2023-09-07 08:40:13.185][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-aarch64/libcrypto.so], hHandleRet[-2041139056]
[2023-09-07 08:40:13.186][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-aarch64/libssl.so], hHandleRet[-2040564496]
[2023-09-07 08:40:13.186][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-aarch64/libcrypto.so]
[2023-09-07 08:40:13.186][INF] SSLTRANSAPI::IsAllAPILoaded, SSL_library_init Unload
[2023-09-07 08:40:13.186][INF] OpenSSL, Not All Function Loaded!
[2023-09-07 08:40:13.186][INF] SSLTRANSAPI::PrintVersion, OpenSSL version info [OpenSSL 1.1.1i  8 Dec 2020]
[2023-09-07 08:40:13.186][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[6], m_fnTLSServerMethod
2023-09-07 08:40:13.422 | DEBUG    | doorbell:authenticate:69 - Login returned user ID: 0
2023-09-07 08:40:13.423 | DEBUG    | doorbell:authenticate:70 - Doorbell serial number: 68834575498451524965775048504948544857864851485051486978715048485255495655, device type: FaceAccessTerminal_1
2023-09-07 08:40:13.424 | INFO     | doorbell:authenticate:72 - Connected to doorbell: Gate
2023-09-07 08:40:13.425 | INFO     | event:__init__:76 - Setting up event handler: Console stdout
2023-09-07 08:40:13.425 | DEBUG    | event:register_handler:206 - Adding event handler ConsoleSTDOUT
2023-09-07 08:40:13.426 | INFO     | mqtt:__init__:96 - Setting up event handler: MQTT
2023-09-07 08:40:13.427 | DEBUG    | mqtt:__init__:108 - Setting up entities for Gate
2023-09-07 08:40:13.428 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-09-07 08:40:13.437][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCVoiceTalk.so] SUCC
[2023-09-07 08:40:13.437][INF] AbilityAnalyze---Init-- start
[2023-09-07 08:40:13.439][DBG] AbilityAnalyze---Init-- over, DeviceList path [/app/lib-aarch64/HCNetSDKCom/LocalXml/DeviceList.xml], load result[0]
[2023-09-07 08:40:13.439][INF] The COM:VoiceTalk ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.441][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCGeneralCfgMgr.so] SUCC
[2023-09-07 08:40:13.441][INF] The COM:HCGeneralCfgMgr ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.443][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCPlayBack.so] SUCC
[2023-09-07 08:40:13.443][INF] The COM:HCPlayback ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.444][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCIndustry.so] SUCC
[2023-09-07 08:40:13.444][INF] The COM:HCIndustry ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.445][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCDisplay.so] SUCC
[2023-09-07 08:40:13.446][INF] The COM:HCDisplay ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.447][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCPreview.so] SUCC
[2023-09-07 08:40:13.447][INF] The COM:Preview ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.448][DBG] CComBase::Load, Load szDllPath[/app/lib-aarch64/HCNetSDKCom/libHCAlarm.so] SUCC
[2023-09-07 08:40:13.449][INF] The COM:HCAlarm ver is 6.1.8.101, 2021_12_10.
[2023-09-07 08:40:13.450][INF] Private connect 192.168.1.128:8000 sock=7 this=0x865ba4a4 cmd=0x117000 port=36926
2023-09-07 08:40:13.459 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Access Controller</deviceName>
<deviceID>255</deviceID>
<model>DS-K1T341AM</model>
<serialNumber>G20047187</serialNumber>
<macAddress>24:28:FD:44:F2:AD</macAddress>
<firmwareVersion>V3.2.30</firmwareVersion>
<firmwareReleasedDate>build 210609</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 191119</encoderReleasedDate>
<deviceType>ACS</deviceType>
<telecontrolID>1</telecontrolID>
<supportBeep>false</supportBeep>
<localZoneNum>0</localZoneNum>
<alarmOutNum>0</alarmOutNum>
<electroLockNum>1</electroLockNum>
<RS485Num>1</RS485Num>
<marketType>2</marketType>
</DeviceInfo>

[2023-09-07 08:40:13.458][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-07 08:40:13.458][ERR] StructureMime BOUNDARY DATA ERROR!
[2023-09-07 08:40:13.522][INF] [0][COM_CoreDevCfg_GetDeviceAbility] AbilityType 0x14, InbufLen=[0], OutbufLen[4096]
[2023-09-07 08:40:13.524][INF] Private connect 192.168.1.128:8000 sock=8 this=0x865ba4a4 cmd=0x11000 port=36928
2023-09-07 08:40:13.530 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-09-07 08:40:13.537][INF] Private connect 192.168.1.128:8000 sock=8 this=0x865ba4a4 cmd=0x117000 port=36938
2023-09-07 08:40:13.545 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <IOOutputPortList version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
</IOOutputPortList>

2023-09-07 08:40:13.546 | DEBUG    | mqtt:__init__:145 - Configuring 0 door switches
2023-09-07 08:40:13.547 | DEBUG    | event:register_handler:206 - Adding event handler MQTT
2023-09-07 08:40:13.547 | DEBUG    | mqtt_input:__init__:21 - Setting up MQTTInput
2023-09-07 08:40:13.548 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-09-07 08:40:13.545][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/IO/outputs], input size[0], max segment length[262144]
[2023-09-07 08:40:13.545][ERR] StructureMime BOUNDARY DATA ERROR!
[2023-09-07 08:40:13.557][INF] Private connect 192.168.1.128:8000 sock=8 this=0x865ba4a4 cmd=0x117000 port=36940
2023-09-07 08:40:13.568 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Access Controller</deviceName>
<deviceID>255</deviceID>
<model>DS-K1T341AM</model>
<serialNumber>G20047187</serialNumber>
<macAddress>24:28:FD:44:F2:AD</macAddress>
<firmwareVersion>V3.2.30</firmwareVersion>
<firmwareReleasedDate>build 210609</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 191119</encoderReleasedDate>
<deviceType>ACS</deviceType>
<telecontrolID>1</telecontrolID>
<supportBeep>false</supportBeep>
<localZoneNum>0</localZoneNum>
<alarmOutNum>0</alarmOutNum>
<electroLockNum>1</electroLockNum>
<RS485Num>1</RS485Num>
<marketType>2</marketType>
</DeviceInfo>

[2023-09-07 08:40:13.568][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-07 08:40:13.568][ERR] StructureMime BOUNDARY DATA ERROR!
2023-09-07 08:40:13.604 | DEBUG    | event:start:227 - Registering callback function using SDK
2023-09-07 08:40:13.607 | DEBUG    | doorbell:setup_alarm:83 - Arming the device via SDK
[2023-09-07 08:40:13.613][INF] Private connect 192.168.1.128:8000 sock=23 this=0x865ba4a4 cmd=0x111021 port=36944
2023-09-07 08:40:13.623 | DEBUG    | input:loop_forever:29 - Waiting for input command
2023-09-07 08:40:14.127 | DEBUG    | event:_handle_callback:192 - Callback invoked from SDK
2023-09-07 08:40:14.129 | WARNING  | event:_cast_alarm_info:160 - Received unhandled command: 20482
2023-09-07 08:40:14.132 | DEBUG    | event:_invoke_handlers:166 - Invoking 2 handlers
2023-09-07 08:40:14.133 | WARNING  | mqtt:unhandled_event:351 - Unknown event from Gate
[2023-09-07 08:40:14.126][INF] Alarm[0] IP[192.168.1.128] data_len[1440] alarm_len[1432] status[400]
2023-09-07 08:40:14.134 | WARNING  | event:unhandled_event:129 - Unknown event from Gate

**Comment by pergolafabio** [comment]
We are indeed trying to collect info from the device to make sensors and switches, but not all commands we send to the device are working... What sensors are working? Do you see the call sensors?

About the gate, do you see z switch? If not, you can configure it manually, by defining the "output_relays: 2", it's in the docs...


About below:

 Received unhandled command: 20482

We are indeed only collecting some important events like motion, zone, inputs,... All the restbis unhandled

**Comment by pergolafabio** [comment]
It's probably an event from below, from ACS...

Do you recognize it?

https://open.hikvision.com/hardware/structures/NET_DVR_ACS_ALARM_INFO.html

**Comment by pergolafabio** [comment]
can you try beta 36? i added those ACS events too, could be maybe interesting?
Can you test and see if the unhandled event is now visible?

**Comment by shizlanski** [comment]
This is the current log. I also added my indoor unit. I changed the output relays as you suggested and that works well. Thanks for your efforts.

```
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 000000</encoderReleasedDate>
<deviceType>DVR</deviceType>
<RS485Num>1</RS485Num>
<telecontrolID>255</telecontrolID>
<alarmOutNum>2</alarmOutNum>
<alarmInNum>8</alarmInNum>
<customizedInfo></customizedInfo>
</DeviceInfo>

2023-09-09 09:32:29.178 | DEBUG    | mqtt:__init__:144 - Configuring 0 door switches
2023-09-09 09:32:29.179 | DEBUG    | mqtt:__init__:162 - Configuring 2 com relays for indoor station
[2023-09-09 09:32:29.174][INF] Private connect 192.168.1.63:8000 sock=11 this=0xaf298b44 cmd=0x117000 port=38162
[2023-09-09 09:32:29.177][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-09 09:32:29.177][ERR] StructureMime BOUNDARY DATA ERROR!
2023-09-09 09:32:29.194 | DEBUG    | event:register_handler:234 - Adding event handler MQTT
2023-09-09 09:32:29.195 | DEBUG    | mqtt_input:__init__:21 - Setting up MQTTInput
2023-09-09 09:32:29.196 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-09-09 09:32:29.205][INF] Private connect 192.168.1.128:8000 sock=17 this=0xaf298b44 cmd=0x117000 port=51548
2023-09-09 09:32:29.219 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Access Controller</deviceName>
<deviceID>255</deviceID>
<model>DS-K1T341AM</model>
<serialNumber>G20047187</serialNumber>
<macAddress>24:28:FD:44:F2:AD</macAddress>
<firmwareVersion>V3.2.30</firmwareVersion>
<firmwareReleasedDate>build 210609</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 191119</encoderReleasedDate>
<deviceType>ACS</deviceType>
<telecontrolID>1</telecontrolID>
<supportBeep>false</supportBeep>
<localZoneNum>0</localZoneNum>
<alarmOutNum>0</alarmOutNum>
<electroLockNum>1</electroLockNum>
<RS485Num>1</RS485Num>
<marketType>2</marketType>
</DeviceInfo>

[2023-09-09 09:32:29.218][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-09 09:32:29.218][ERR] StructureMime BOUNDARY DATA ERROR!
2023-09-09 09:32:29.256 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
2023-09-09 09:32:29.268 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Embedded Net VIS</deviceName>
<deviceID>48513037-3439-3536-3934-2428fd452d51</deviceID>
<model>DS-KH8350-WTE1</model>
<serialNumber>DS-KH8350-WTE10120210619WRQ07495694CLU</serialNumber>
<macAddress>24:28:fd:45:2d:51</macAddress>
<firmwareVersion>V2.1.20</firmwareVersion>
<firmwareReleasedDate>build 210420</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 000000</encoderReleasedDate>
<deviceType>DVR</deviceType>
<RS485Num>1</RS485Num>
<telecontrolID>255</telecontrolID>
<alarmOutNum>2</alarmOutNum>
<alarmInNum>8</alarmInNum>
<customizedInfo></customizedInfo>
</DeviceInfo>

[2023-09-09 09:32:29.265][INF] Private connect 192.168.1.63:8000 sock=32 this=0xaf298b44 cmd=0x117000 port=38164
[2023-09-09 09:32:29.268][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-09 09:32:29.268][ERR] StructureMime BOUNDARY DATA ERROR!
2023-09-09 09:32:29.303 | DEBUG    | event:start:255 - Registering callback function using SDK
2023-09-09 09:32:29.305 | DEBUG    | doorbell:setup_alarm:83 - Arming the device via SDK
[2023-09-09 09:32:29.308][INF] Private connect 192.168.1.128:8000 sock=47 this=0xaf298b44 cmd=0x111021 port=51564
2023-09-09 09:32:29.317 | DEBUG    | doorbell:setup_alarm:83 - Arming the device via SDK
2023-09-09 09:32:29.324 | DEBUG    | input:loop_forever:29 - Waiting for input command
[2023-09-09 09:32:29.320][INF] Private connect 192.168.1.63:8000 sock=50 this=0xaf299060 cmd=0x111020 port=38178
[2023-09-09 09:32:29.818][INF] Alarm[0] IP[192.168.1.128] data_len[1440] alarm_len[1432] status[400]
2023-09-09 09:32:29.819 | DEBUG    | event:_handle_callback:220 - Callback invoked from SDK
2023-09-09 09:32:29.823 | DEBUG    | event:_invoke_handlers:192 - Invoking 2 handlers
2023-09-09 09:32:29.824 | INFO     | event:acs_alarm:142 - ACS alarm from Gate
2023-09-09 09:32:29.825 | DEBUG    | mqtt:acs_alarm:217 - Access control event occured, trying to find the event for Major: 3 : Minor: 1049
2023-09-09 09:32:29.827 | INFO     | mqtt:acs_alarm:228 - Access control event: MAJOR_OPERATION found with event: MINOR_REMOTE_ACTUAL_GUARD
2023-09-09 09:32:29.828 | DEBUG    | sdk.utils:call_ISAPI:125 - Request body: 
[2023-09-09 09:32:29.833][INF] Private connect 192.168.1.128:8000 sock=51 this=0xaf29957c cmd=0x117000 port=51578
2023-09-09 09:32:29.845 | DEBUG    | sdk.utils:call_ISAPI:165 - Response output: <DeviceInfo version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
<deviceName>Access Controller</deviceName>
<deviceID>255</deviceID>
<model>DS-K1T341AM</model>
<serialNumber>G20047187</serialNumber>
<macAddress>24:28:FD:44:F2:AD</macAddress>
<firmwareVersion>V3.2.30</firmwareVersion>
<firmwareReleasedDate>build 210609</firmwareReleasedDate>
<encoderVersion>V1.0</encoderVersion>
<encoderReleasedDate>build 191119</encoderReleasedDate>
<deviceType>ACS</deviceType>
<telecontrolID>1</telecontrolID>
<supportBeep>false</supportBeep>
<localZoneNum>0</localZoneNum>
<alarmOutNum>0</alarmOutNum>
<electroLockNum>1</electroLockNum>
<RS485Num>1</RS485Num>
<marketType>2</marketType>
</DeviceInfo>

[2023-09-09 09:32:29.845][DBG] SimpleSTDCommandToDvr with out cmd[GET /ISAPI/System/deviceInfo], input size[0], max segment length[262144]
[2023-09-09 09:32:29.845][ERR] StructureMime BOUNDARY DATA ERROR!
2023-09-09 09:32:29.854 | DEBUG    | mqtt:handle_device_trigger:409 - Invoking device trigger {'name': 'MAJOR_OPERATION MINOR_REMOTE_ACTUAL_GUARD', 'type': '', 'subtype': 'MAJOR_OPERATION MINOR_REMOTE_ACTUAL_GUARD'}
```

**Comment by pergolafabio** [comment]
Perfect , I also see the unknown event is handled...

Access control event: MAJOR_OPERATION found with event: MINOR_REMOTE_ACTUAL_GUARD


I will make a new stable build 3.0.x ,later , if its ready, dont use the beta anymore! :-)

Thx for feedback

**Comment by pergolafabio** [comment]
Gonna reopen this issues , I see your locks as xml below, i will try to change the code, so it uses below to configure the locks...

Can you stay on beta for now? I try to make a build next week, so you don't need to manually configure the locks...

<electroLockNum>1</electroLockNum>

**Comment by pergolafabio** [comment]
Is it possible to remove the output relays from your config, then restart addon and then paste me the complete debug log from start?

Afterwards, just enable the lock back manually in the config... want to know what's going on with your model

**Comment by pergolafabio** [comment]
Btw, how many locks does your device have?

**Comment by pergolafabio** [comment]
can you try rub beta 39?
Just run it like below, no debug needed, otherwhise i will see to much info

```
log_level: INFO
sdk_log_level: NONE

```

it should give output like:

```

2023-09-10 12:42:02.380 | INFO     | doorbell:sdk_device_ability:247 - Response url for sdk_device_ability: <IpViewDevAbility version="2.0">
<LocalAbility>
<inputVolume min="0" max="10"/>
<outputVolume min="0" max="10"/>
<talkVolume min="0" max="10"/>
</LocalAbility>
<VideoIntercom>
<DeviceID>
<enabled>true</enabled>
<supportUnitType opt="OutDoorDevice,OutDoorFenceDevice"/>
<OutDoorDevice>
<period min="1" max="9"/>
<buildingNum min="1" max="999"/>
<unitNum min="1" max="99"/>
<floorNum min="-10" max="10"/>
<devIndex min="0" max="16"/>
</OutDoorDevice>
<OutDoorFenceDevice>
<period min="1" max="9"/>
<devIndex min="1" max="99"/>
</OutDoorFenceDevice>
</DeviceID>
<PrivilegePwd>
<pwdType opt="public1,public2,public3,public4,public5,public6,public7,public8,public9,public10,public11,public12,public13,public14,public15,public16"/>
<pwdLen min="4" max="6"/>
</PrivilegePwd>
<OperationTime>
<messageTime min="30" max="60"/>
<talkTime min="90" max="120"/>
<maxRingTime min="65" max="255"/>
</OperationTime>
<RelateDevice>
<manageUnitIP opt="ipv4"/>
<sipServerIP opt="ipv4"/>
<centerIP opt="ipv4"/>
<centerPort min="1" max="65535"/>
</RelateDevice>
<ControlGateway>
<gatewayIndex min="1"/>
<command opt="open,normalOpen,resume"/>
<controlSrc>true</controlSrc>
<controlType opt="monitor,calling"/>
<lockType opt="normal"/>
</ControlGateway>
<IOIn>
<IOInNo attri="readonly" min="1" max="4"/>
<useType opt="magneticStatus"/>
<NodeList>
<Node>
<id>1</id>
<name>AI1</name>
<useType opt="magneticStatus"/>
</Node>
<Node>
<id>2</id>
<name>AI2</name>
<useType opt="magneticStatus"/>
</Node>
<Node>
<id>3</id>
<name>AI3</name>
<useType opt="openDoorBtn"/>
</Node>
<Node>
<id>4</id>
<name>AI4</name>
<useType opt="openDoorBtn"/>
</Node>
</NodeList>
</IOIn>
<IOOut>
<IOOutNo attri="readonly" min="1" max="2"/>
<useType opt="electricLock"/>
<NodeList>
<Node>
<id>1</id>
<name>DOOR1</name>
<useType opt="electricLock"/>
</Node>
<Node>
<id>2</id>
<name>DOOR2</name>
<useType opt="disabled,electricLock"/>
</Node>
</NodeList>
</IOOut>
<ElevatorControl>
<elevatorNo attri="readonly" min="1" max="4"/>
<interfaceType opt="network"/>
<networkProtocol opt="private,custom"/>
<serverIP opt="ipv4,ipv6"/>
<serverPort min="1" max="65535"/>
<negativeFloor min="0" max="10"/>
<elevatorControlType opt="DS-K2210"/>
<userName min="1" max="63"/>
<password min="1" max="63"/>
<isSupportNetWork opt="DS-K2210"/>
<isSupportNegativeFloor opt="DS-K2210"/>
</ElevatorControl>
<VideoCall>
<enabled opt="true"/>
<supportCmd opt="Request,Cancel,Answer,Decline,Timeout,Bye,DeviceIsBusy,ClientIsBusy"/>
</VideoCall>
<supportVideoFormat opt="P,N"/>
<CallRoomConfig>
<keyNo min="1" max="1"/>
<roomNo min="1" max="9999"/>
<callManageCenter opt="true,false"/>
</CallRoomConfig>
</VideoIntercom>
<UploadAlarmCfg>
<UploadDoorNotCloseAlarm opt="true,false"/>
</UploadAlarmCfg>
<NoNeedReboot>
<videoResolutionChange opt="true"/>
<videoFrameRateChange opt="true"/>
</NoNeedReboot>
</IpViewDevAbility>


```

**Comment by shizlanski** [comment]
Ok I got beta 39, took out the relays and indoor unit, so it's just the outdoor DS-K1T341AM.
Log:

```
2023-09-12 10:12:32.503 | DEBUG    | config:load_mqtt_config:130 - Loading MQTT configuration from supervisor
2023-09-12 10:12:32.504 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2023-09-12 10:12:32.537 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: aarch64
hpr tls index{3}
loop[2] find 2 mac and 0 ip
2023-09-12 10:12:33.845 | INFO     | doorbell:authenticate:72 - Connected to doorbell: Gate
2023-09-12 10:12:33.846 | INFO     | event:__init__:87 - Setting up event handler: Console stdout
2023-09-12 10:12:33.847 | INFO     | mqtt:__init__:95 - Setting up event handler: MQTT
2023-09-12 10:12:33.967 | INFO     | doorbell:sdk_device_ability:247 - Response url for sdk_device_ability: <IpViewDevAbility version="2.0">	
<LocalAbility>	    
<inputVolume min="0" max="10"/>		
<outputVolume min="0" max="10"/>	
</LocalAbility>	
<VideoIntercom>		
<DeviceID>			
<enabled>true</enabled>			
<supportUnitType opt="OutDoorDevice,OutDoorFenceDevice"/>			
<OutDoorDevice>            	
<period min="1" max="9"/>            	
<buildingNum min="1" max="999"/>            	
<unitNum min="1" max="99"/>            	
<floorNum min="-10" max="10"/>            	
<devIndex  min="0" max="99"/>            
</OutDoorDevice>            
<OutDoorFenceDevice>            	
<period min="1" max="9"/>            	
<devIndex  min="1" max="99"/>            
</OutDoorFenceDevice>        
</DeviceID>        
<RelateDevice>	        
<outdoorUnitIP  opt="ipv4"/>        	
<manageUnitIP opt="ipv4"/>        	
<sipServerIP opt="ipv4"/>        
</RelateDevice>    
</VideoIntercom>
</IpViewDevAbility>
2023-09-12 10:12:34.001 | INFO     | doorbell:isapi_io_outputs:259 - Response url for /ISAPI/System/IO/outputs: <IOOutputPortList version="2.0" xmlns="http://www.isapi.org/ver20/XMLSchema">
</IOOutputPortList>

2023-09-12 10:12:34.575 | INFO     | mqtt:acs_alarm:228 - Access control event: MAJOR_OPERATION found with event: MINOR_REMOTE_ACTUAL_GUARD
2023-09-12 10:12:34.628 | INFO     | event:acs_alarm:142 - ACS alarm from Gate
```

**Comment by pergolafabio** [comment]
Hmm, no locks to see there in that output... your device only have 1 relay right? I will make beta 40, today, so you can test later...

This info is correct for your device?

<electroLockNum>1</electroLockNum>

**Comment by shizlanski** [comment]
I believe the device has 2 relays available but currently I only have 1 in use. It works if I manually add it.

**Comment by pergolafabio** [comment]
yea, i'm trying to make support for those device to create the switches automaticly :-)

**Comment by pergolafabio** [comment]
can you try again with beta 40 ? remove config for output relays and user:

```
log_level: INFO
sdk_log_level: NONE
```

can you show me log also, i have added the a new call isapi method for elektrolocks

**Comment by pergolafabio** [comment]
Hi, do you have an update for me? if this works, i can release a new stable build

**Comment by pergolafabio** [comment]
gonna close for now, let me know if you still can test it
