### ISSUE TITLE
EZVIZ HP7 - unsupported

### ISSUE THREAD

**Issue by Adrien2575** [pergolafabio/Hikvision-Addons#232]
### What happened?

Hello !
My device is an hezviz hp7 intercom (a brand using hikvision hardware).
I can connect with the HCNetSDK but got the following error in your very promising software:

**ValueError: 2211 is not a valid DeviceType**

Any chance to see this device included?
Thanks a lot!
Adrien

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.18

### Installation type

Docker container (standalone)

### Relevant log output

```Text
[2024-11-07 20:53:21.216][INF] Login dev 192.168.1.144:8000.


[2024-11-07 20:53:21.216][INF] dwTotalNum[2048]


[2024-11-07 20:53:21.220][INF] Private connect 192.168.1.144:8000 sock=135 this=0x17cc86c4 cmd=0x10000 port=40844


[2024-11-07 20:53:21.220][INF] LogonDev1 in[192.168.1.144:8000]


[2024-11-07 20:53:21.268][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[lib-amd64/libcrypto.so], hHandleRet[399320400]


[2024-11-07 20:53:21.290][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[lib-amd64/libssl.so], hHandleRet[399321616]


[2024-11-07 20:53:21.291][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[lib-amd64/libcrypto.so]


[2024-11-07 20:53:21.291][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[lib-amd64/libssl.so]


[2024-11-07 20:53:21.291][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload


[2024-11-07 20:53:21.291][INF] OpenSSL, Not All Function Loaded!


[2024-11-07 20:53:21.291][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]


[2024-11-07 20:53:21.291][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23


Traceback (most recent call last):

  File "/app/main.py", line 111, in <module>

    asyncio.run(main_loop())

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run

    return loop.run_until_complete(main)

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete

    return future.result()

  File "/app/main.py", line 96, in main_loop

    await main()

  File "/app/main.py", line 47, in main

    doorbell.authenticate()

  File "/app/doorbell.py", line 73, in authenticate

    self._type = DeviceType(self._device_info.wDevType)

  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__

    return cls.__new__(cls, value)

  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__

    raise ve_exc

ValueError: 2211 is not a valid DeviceType
```

**Comment by pergolafabio** [comment]
hmm, i can add it , but i dont think its going to wotk, ezviz uses a different SDK i believe

**Comment by pergolafabio** [comment]
i just added beta 70 , do a refresh addon, you should see it listed:

version: '3.0.0-beta.70'

**Comment by pergolafabio** [comment]
camera stream is not coming from my sdk, thats just rtsp

**Comment by Adrien2575** [comment]
Thanks ! I got the following error indeed on the event side :2024-11-07 21:16:27.672 | ERROR    | __main__:main_loop:100 - Error while listening to events in Outdoor: Device does not support this function. Error code: 23I guess that’s what you feared ?From the Hikvision sdk (the C sharp examples) I’m able to see the camera feed whereas my camera does not open its 554 port, only 8000 hence I thought you plugin would get the feed another way than rtsp. Thanks anyway !Le 7 nov. 2024 à 22:12, Pergola Fabio ***@***.***> a écrit :﻿
camera stream is not coming from my sdk, thats just rtsp

**Comment by pergolafabio** [comment]
thats too bad :-(

sorry , but i believe there is an ezviz cloud integration on HA? maybe you can try it to get the stream?
