### ISSUE TITLE
10515 is not a Valid DeviceType for K1T341BM and KH6350！

### ISSUE THREAD

**Issue by lccox** [pergolafabio/Hikvision-Addons#234]
### What happened?

When I tried to add the access control device K1T341BM and the indoor station KH6350, the system prompted an error: ValueError: 10515 is not a valid DeviceType, which prevents me from starting the addon.
The screenshot content is as follows:
![screenshot](https://github.com/user-attachments/assets/9b1b2290-e8d3-446a-94d8-f17d7cfcfe95)

**How should I proceed? Thanks very much!**

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.18

### Installation type

Home Assistant add-on

### Relevant log output

```Text
2024-11-19 11:15:12.767 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
loop[2] find 2 mac and 1 ip
Traceback (most recent call last):
  File "/app/main.py", line 111, in <module>
    asyncio.run(main_loop())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 96, in main_loop
    await main()
  File "/app/main.py", line 47, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 73, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 10515 is not a valid DeviceType
```

**Comment by pergolafabio** [comment]
just pushed version .19 , can you try ?

**Comment by lccox** [comment]
Thank you very much! K1T341BM is now supported in version 0.19. I truly appreciate your contributions to this addon.

**Comment by lccox** [comment]
> just pushed version .19 , can you try ?


Thank you very much! K1T341BM is now supported in version 0.19. I truly appreciate your contributions to this addon.
