### ISSUE TITLE
Support K1T502

### ISSUE THREAD

**Issue by liorfr-monday** [pergolafabio/Hikvision-Addons#239]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Add-on

Doorbell

### Your feature request

Hi

I see that K1T502 is not supported.
Do you plan to support it?

**Comment by pergolafabio** [comment]
Have you tried it, maybe it works, I don't have a list of working devices, I only have 1 personal device, its a generic SDK

**Comment by liorfr-monday** [comment]
I tried and get an error:
```
loop[2] find 2 mac and 1 ip
Traceback (most recent call last):
  File "/app/main.py", line 111, in <module>
    asyncio.run(main_loop())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 96, in main_loop
    await main()
  File "/app/main.py", line 47, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 74, in authenticate
    self._type = DeviceType(self._device_info.wDevType)
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 884 is not a valid DeviceType
```
And I see this in the code:
```
class DeviceType(IntEnum):
    OUTDOOR = 603
    INDOOR = 602
    VillaVTO = 605
    # K1T502 = 884 (unsupported)
    K1T671MF = 896
    K1T341AM = 10503
    K1T341M = 10510
    K1T341BM = 10515
    K1T343 = 10533
    K1T673 = 10534
    K1T342 = 10538
    K1T670 = 10552
    HD = 31
    AccessControlTerminal = 861
```
