### ISSUE TITLE
Safire  SF-VIK001-S-2 

### ISSUE THREAD

**Issue by Gustemps** [pergolafabio/Hikvision-Addons#74]
Is this doorbell compatible?
it's like DS-KD8003-IME2 (part of the kit: DS-KIS702)

**Comment by Gustemps** [comment]
Log:
2023-03-02 10:56:55.100 | DEBUG    | __main__:main:24 - Importing Hikvision SDK
2023-03-02 10:56:55.115 | INFO     | sdk.utils:loadSDK:44 - Using OS: Linux with architecture: x86_64
2023-03-02 10:56:55.116 | DEBUG    | sdk.utils:loadSDK:57 - Loading library from lib-amd64/libhcnetsdk.so
2023-03-02 10:56:55.156 | DEBUG    | __main__:main:28 - Hikvision SDK loaded
2023-03-02 10:56:55.157 | DEBUG    | sdk.utils:setupSDK:83 - Initializing SDK
loop[2] find 2 mac and 0 ip
2023-03-02 10:56:55.180 | DEBUG    | sdk.utils:setupSDK:97 - SDK initialized
[2023-03-02 10:56:55.180][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/lib/x86_64-linux-gnu/libz.so.1.2.11], hHandleRet[600053952]
[2023-03-02 10:56:55.180][INF] The COM:HCCoreBase ver is 6.1.4.15, 2020_03_05. Async:1.
[2023-03-02 10:56:55.180][INF] The COM:Core ver is 6.1.6.45, 2021_03_02. Async:1.
[2023-03-02 10:56:55.180][INF] This HCNetSDK ver is 6.1.6.45 Ver 2021_03_02.
2023-03-02 10:56:55.182 | DEBUG    | doorbell:__init__:38 - Setting up doorbell: inter
2023-03-02 10:56:55.183 | DEBUG    | doorbell:authenticate:45 - Logging into doorbell
[2023-03-02 10:56:55.183][INF] Login dev 192.168.1.79:8000.
[2023-03-02 10:56:55.183][INF] dwTotalNum[2048]
[2023-03-02 10:56:55.185][INF] Private connect 192.168.1.79:8000 sock=135 this=0x24034f74 cmd=0x10000 port=57058
[2023-03-02 10:56:55.185][INF] LogonDev1 in[192.168.1.79:8000]
[2023-03-02 10:56:55.186][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libcrypto.so], hHandleRet[604237312]
[2023-03-02 10:56:55.186][DBG] CCoreGlobalCtrlBase::LoadDSo, HPR_LoadDSo Succ, Path[/app/lib-amd64/libssl.so], hHandleRet[604238544]
[2023-03-02 10:56:55.186][INF] SSLTRANSAPI::LoadAPI, libeay, Load Real Path[/app/lib-amd64/libcrypto.so]
[2023-03-02 10:56:55.187][INF] SSLTRANSAPI::LoadAPI, libssl, Load Real Path[/app/lib-amd64/libssl.so]
[2023-03-02 10:56:55.187][INF] SSLTRANSAPI::IsAllAPILoaded, OpenSSL_version Unload
[2023-03-02 10:56:55.187][INF] OpenSSL, Not All Function Loaded!
[2023-03-02 10:56:55.187][INF] SSLTRANSAPI::PrintVersion, SSLeay_version info [OpenSSL 1.0.2t  10 Sep 2019]
[2023-03-02 10:56:55.187][INF] CSSLTrans::SSLCtxInit, dwSSLVersion[0], m_fnClientMethodV23
Traceback (most recent call last):
  File "/app/main.py", line 85, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/main.py", line 40, in main
    doorbell.authenticate()
  File "/app/doorbell.py", line 56, in authenticate
    raise RuntimeError(f"SDK error code {self._sdk.NET_DVR_GetLastError()}")
RuntimeError: SDK error code 1
[2023-03-02 10:56:55.437][ERR] LogonDev1[192.168.1.79]
[2023-03-02 10:56:55.437][ERR] [192.168.1.79:8000]PRO_LoginHikDevice fail[err=1].[0x-0000001,0x-0000001]
[2023-03-02 10:56:55.437][ERR] CMemberMgrBase::AllocIndex2, MemberStart Failed, iIndex[0]
[2023-03-02 10:56:55.488][INF] COM_Logout[-1][1]

**Comment by pergolafabio** [comment]
Hi, no idea if that one is compatible :-)

But error code 1 means, incorrect username/password ? Can you check the "admin" password again ?

**Comment by Gustemps** [comment]
Now i get a 
PRO_LoginHikDevice fail[err=153].[0x-0000001,0x-0000001]

Error....
What does it mean?

**Comment by pergolafabio** [comment]
NET_ERR_USERNAME_LOCKED	153	The user name is locked.

**Comment by mion00** [comment]
We have just released a new beta version `3.0.0-beta.6` containing with clearer error messages.
Please try to update you add-on and retry again.

**Comment by pergolafabio** [comment]
Also disable the watchdog on the addon, because if it failed to start, it will restart over and over again... That's why probably your account is locked...

If all works, then enable it again...

**Comment by pergolafabio** [comment]
gonna close this one, let us know if there is still an issue
